resetUrl: http://localhost:8080/backend/auth/reset?token=
verifyUrl: http://localhost:8080/backend/auth/verify?token=

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/invita
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none

  cache:
    cache-names: password_reset_token, verify_user_token
    caffeine:
      spec: maximumSize=500,expireAfterAccess=300s

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080
  servlet:
    context-path: /backend
